spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_telegram_test_task
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  application:
    name: test_task
server:
  port: 8085
telegram:
  bot:
    token: 7556252840:AAGNQLvUEyLYSNZkGoc2JYJDt9jUt08kGbI


